/**
 * Initialize client side namespace for waartaa
 */
waartaa = typeof(waartaa) == 'undefined'? {}: waartaa;
waartaa['chat'] = {};
waartaa['IRC_COMMANDS'] = {
  'ADMIN': '',
  'AWAY': '',
  'CNOTICE': '',
  'CPRIVMSG': '',
  'CONNECT': '',
  'DIE': '',
  'ENCAP': '',
  'ERROR': '',
  'HELP': '',
  'INFO': '',
  'INVITE': '',
  'ISON': '',
  'JOIN': '',
  'KICK': '',
  'KILL': '',
  'KNOCK': '',
  'LINKS': '',
  'LIST': '',
  'LUSERS': '',
  'MODE': '',
  'MOTD': '',
  'NAMES': '',
  'NAMESX': '',
  'NICK': '',
  'NOTICE': '',
  'OPER': '',
  'PART': '',
  'PASS': '',
  'PING': '',
  'PONG': '',
  'PRIVMSG': '',
  'QUIT': '',
  'REHASH': '',
  'RESTART': '',
  'RULES': '',
  'SERVER': '',
  'SERVICE': '',
  'SERVLIST': '',
  'SQUERY': '',
  'SQUIT': '',
  'SETNAME': '',
  'SILENCE': '',
  'STATS': '',
  'SUMMON': '',
  'TIME': '',
  'TOPIC': '',
  'TRACE': '',
  'UHNAMES': '',
  'USER': '',
  'USERHOST': '',
  'USERIP': '',
  'USERS': '',
  'VERSION': '',
  'WALLOPS': '',
  'WATCH': '',
  'WHO': '',
  'WHOIS': '',
  'WHOWAS': '',
};
